#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 
SOURCE_ROOT="/data/nekbone/src/" 

# Fortran compiler
F77="mpif77"

# C compiler
CC="mpicc"

# CUDA Compiler
NVCC="/opt/cuda/5.5/bin/nvcc -gencode=arch=compute_10,code=sm_10 -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_35,code=compute_35"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
#PPLIST="?" 


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# enable CUDA (default false)
IFCUDA="true"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
USR_LFLAGS="-lstdc++ -L/opt/cuda/5.5/lib64 -lcuda -lcudart -lcublas /data/magma/lib/libmagma.a"

# generic compiler flags
G="-g -I/data/magma/include -DHAVE_CUBLAS"

# optimization flags
#OPT_FLAGS_STD=""
#OPT_FLAGS_MAG=""

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
